[tox]
minversion = 3.7
envlist = py39-ansible{29,210}
skipsdist = true

[testenv]
passenv = *
deps =
    ansible29: ansible==2.9.*
    ansible210: ansible==2.10.*
    molecule[docker]
    molecule-podman
    pytest
    pytest-testinfra
commands =
    molecule test -s tox
