---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
verifier:
  name: ansible
  playbooks:
    verify: ../default/verify.yml
